### ISSUE TITLE
After Installing i got 3 default environments

### ISSUE THREAD

**Issue by ninjaonsafari** [JcRichards1991/Our.Shield#15]
I installed the core and mediaprotect package via nuget. And after the installation i got 3 default environments.

Is there a setting i'm missing?

![image](https://user-images.githubusercontent.com/2211563/28709329-23878bba-7380-11e7-9851-4df81be9167f.png)

**Comment by ninjaonsafari** [comment]
We just deployed the website and now i got 5 envs...

**Comment by JcRichards1991** [comment]
Hi @ninjaonsafari 

I've just tried to replicate this on a fresh install of umbraco v7.5.14 and only installing Our.Shield.Core & Our.Shield.MediaProtection via nuget, this worked as expected - only one environment (default) was created.

Our.Shield.Core uses umbraco migrations to create the tables within the database, as part of the environment migration, it adds a new entry to the table (the default environment). As it has created several default environments, this obviously, has ran the environment migration several times.

To assist in getting to the bottom of this issue, could you:

1. Provide the version of umbraco you're using
2. A screenshot of your umbracoMigration table

> Where are the envs collected or how can i configure them?

At present, you cannot configure any environments. The environments are stored within the database in a table called ShieldEnvironment. You could delete the duplicated environments by using the following SQL commands

`DELETE FROM ShieldConfiguration
WHERE EnvironmentId != 1`

`DELETE FROM ShieldEnvironment
WHERE Id != 1`

**Comment by ninjaonsafari** [comment]
Umbraco Version: 7.6.1

id	name	createDate	version
1	Umbraco	2017-01-06 13:38:53.523	7.5.6
2	Umbraco	2017-02-22 16:57:22.737	7.5.10
3	Umbraco	2017-03-07 14:02:19.427	7.5.11
4	Umbraco	2017-05-08 10:23:04.570	7.6.0
5	Umbraco	2017-05-10 15:45:53.097	7.6.1
6	ShieldMediaProtection	2017-07-28 10:15:03.253	1.0.0

**Comment by ninjaonsafari** [comment]
it looks like everytime the apppool gets restarted it creates a new envs...

**Comment by JcRichards1991** [comment]
Hi @ninjaonsafari 

As an immediate fix to your issue, you'll need to add a new entry to umbracoMigration table, which is the main shield migration entry, using the following Sql Command:

`INSERT INTO umbracoMigration (name, createDate, version)
VALUES ('Shield', GETDATE(), '1.0.0');`

> possible location: https://github.com/JcRichards1991/Our.Shield/blob/7274cb58ad37636ab07f5249db6428c72190e3c9/src/Our.Shield.Core/UI/Register.cs#L18

This informs Umbraco to create a new application (custom section) within the backoffice. The issue will be somewhere within this file:

https://github.com/JcRichards1991/Our.Shield/blob/7274cb58ad37636ab07f5249db6428c72190e3c9/src/Our.Shield.Core/Persistance/Data/Migration.cs

**Comment by JcRichards1991** [comment]
@ninjaonsafari 

As you can see in the previous link, on line 55, it should be logging the fact it has failed. could you also provide the exception being thrown within the logs

Reference: https://github.com/JcRichards1991/Our.Shield/blob/7274cb58ad37636ab07f5249db6428c72190e3c9/src/Our.Shield.Core/Persistance/Data/Migration.cs#L55

**Comment by ninjaonsafari** [comment]
```
 2017-07-28 13:21:58,657 [P14624/D10/T150] ERROR Umbraco.Core.Persistence.UmbracoDatabase - Exception (2e61407d).
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'ShieldJournal'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClassa.<ExecuteScalarWithRetry>b__9()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.Database.ExecuteScalar[T](String sql, Object[] args)
ClientConnectionId:a9e53b8e-3564-4389-97de-eefd07b7a43a
Error Number:208,State:1,Class:16
 2017-07-28 13:21:58,657 [P14624/D10/T150] ERROR Our.Shield.Core.Persistance.Business.JournalContext - Error getting journals for environment with Id: ; App Id: 
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'ShieldJournal'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClassa.<ExecuteScalarWithRetry>b__9()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.Database.ExecuteScalar[T](String sql, Object[] args)
   at Umbraco.Core.Persistence.Database.Page[T](Int64 page, Int64 itemsPerPage, String sql, Object[] args)
   at Our.Shield.Core.Persistance.Business.JournalContext.GetListingResults(Nullable`1 environmentId, String appId, Int32 page, Int32 itemsPerPage, Type type, Int32& totalPages)
ClientConnectionId:a9e53b8e-3564-4389-97de-eefd07b7a43a
Error Number:208,State:1,Class:16
```

**Comment by JcRichards1991** [comment]
Have successfully replicated issue. This isn't present when using SqlCe as database. Errors when using i.e. Sql2014 Express database. Full log of error (broken up)

CREATE Journal table:

2017-07-28 13:59:37,436 [P1340/D2/T1] INFO  Umbraco.Core.Persistence.Database - Create Table sql -1:
 CREATE TABLE [ShieldJournal] ([Id] INTEGER NOT NULL IDENTITY(1,1),
[AppId] NVARCHAR(256) NOT NULL,
[EnvironmentId] INTEGER NOT NULL,
[Datestamp] DATETIME NOT NULL,
[Value] NVARCHAR(255) NOT NULL)
 2017-07-28 13:59:37,450 [P1340/D2/T1] INFO  Umbraco.Core.Persistence.Database - Primary Key sql -1:
 ALTER TABLE [ShieldJournal] ADD CONSTRAINT [PK_ShieldJournal] PRIMARY KEY CLUSTERED ([Id])
 2017-07-28 13:59:37,474 [P1340/D2/T1] INFO  Umbraco.Core.Persistence.Migrations.Initial.BaseDataCreation - Creating data in table ShieldJournal
 2017-07-28 13:59:37,474 [P1340/D2/T1] INFO  Umbraco.Core.Persistence.Migrations.Initial.BaseDataCreation - Done creating data in table ShieldJournal
 2017-07-28 13:59:37,495 [P1340/D2/T1] INFO  Umbraco.Core.Persistence.Database - Create Index sql -1:
 CREATE NONCLUSTERED INDEX [IX_Shield_AppId] ON [ShieldJournal] ([AppId])
 2017-07-28 13:59:37,508 [P1340/D2/T1] INFO  Umbraco.Core.Persistence.Database - Create Index sql -1:
 CREATE NONCLUSTERED INDEX [IX_Shield_EnvironmentId] ON [ShieldJournal] ([EnvironmentId])
 
 Exception:
 
 2017-07-28 13:59:37,544 [P1340/D2/T1] ERROR Umbraco.Core.Persistence.UmbracoDatabase - Exception (9cfdc056).
 System.Data.SqlClient.SqlException (0x80131904): Cannot create more than one clustered index on table 'ShieldJournal'. Drop the existing clustered index 'PK_ShieldJournal' before creating another.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action'1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action'1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource'1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in c:\Code\github\SamSaffron\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbCommand.cs:line 279
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClass1.<ExecuteNonQueryWithRetry>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteNonQueryWithRetry(IDbCommand command, RetryPolicy cmdRetryPolicy, RetryPolicy conRetryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteNonQueryWithRetry(IDbCommand command, RetryPolicy retryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteNonQueryWithRetry(IDbCommand command)
   at Umbraco.Core.Persistence.Database.Execute(String sql, Object[] args)
ClientConnectionId:ac8f1517-530d-4a7a-8c63-430749e39da5
Error Number:1902,State:3,Class:16

Log added by Our.Shield.Core Migration

 2017-07-28 13:59:37,561 [P1340/D2/T1] ERROR Our.Shield.Core.Persistance.Data.Migration - Error running Shield migration
System.Data.SqlClient.SqlException (0x80131904): Cannot create more than one clustered index on table 'ShieldJournal'. Drop the existing clustered index 'PK_ShieldJournal' before creating another.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action'1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action'1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in c:\Code\github\SamSaffron\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbCommand.cs:line 279
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClass1.<ExecuteNonQueryWithRetry>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func'1 func)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteNonQueryWithRetry(IDbCommand command, RetryPolicy cmdRetryPolicy, RetryPolicy conRetryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteNonQueryWithRetry(IDbCommand command, RetryPolicy retryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteNonQueryWithRetry(IDbCommand command)
   at Umbraco.Core.Persistence.Database.Execute(String sql, Object[] args)
   at Umbraco.Core.Persistence.Database.Execute(Sql sql)
   at Umbraco.Core.Persistence.DatabaseSchemaHelper.CreateTable(Boolean overwrite, Type modelType)
   at Our.Shield.Core.Persistance.Data.Migrations.JournalMigration.Up()
   at Umbraco.Core.Persistence.Migrations.MigrationBase.GetUpExpressions(IMigrationContext context)
   at Umbraco.Core.Persistence.Migrations.MigrationRunner.InitializeMigrations(List'1 migrations, Database database, DatabaseProviders databaseProvider, Boolean isUpgrade)
   at Umbraco.Core.Persistence.Migrations.MigrationRunner.Execute(Database database, DatabaseProviders databaseProvider, Boolean isUpgrade)
   at Umbraco.Core.Persistence.Migrations.MigrationRunner.Execute(Database database, Boolean isUpgrade)
   at Our.Shield.Core.Persistance.Data.Migration.RunMigrations(ISqlSyntaxProvider sqlSyntax, IMigrationEntryService migrationEntryService, ILogger logger)
ClientConnectionId:ac8f1517-530d-4a7a-8c63-430749e39da5

**Comment by ninjaonsafari** [comment]
Nice!
When could you provide a fix for that?

**Comment by JcRichards1991** [comment]
Hi @ninjaonsafari 

I've got a fix for this locally, I just need to do some more testing before I commit & release a new nuget version.

I'll update this thread once the new release is live.

**Comment by ninjaonsafari** [comment]
as a quick fix i added the `shield` to the `umbracoMigration` table.

> INTO umbracoMigration (name, createDate, version) VALUES ('Shield', GETDATE(), '1.0.0');

it works, but without the journal.

**Comment by JcRichards1991** [comment]
Our.Shield should still function as expected with the missing shield journal table, there's quite a bit of error handling around the data-layer.

The next release should handle the migrations correctly from v1.0.0 to v1.0.1 which should create the missing table for you. This will hopefully be released by end of play today, otherwise, should be ready for Monday

**Comment by ninjaonsafari** [comment]
Thanks bud! Your rock :raised_hand:!

**Comment by JcRichards1991** [comment]
Our.Shield.Core v1.0.1 has been released - https://www.nuget.org/packages/Our.Shield.Core/1.0.1 - after upgrading to the new version, you will need to re-save Media Protection's configuration.

Note: As of writing this, nuget is indexing the package, so may not be available straight away :)

**Comment by ninjaonsafari** [comment]
Awesome the new version works!

**Comment by JcRichards1991** [comment]
That's excellent news, I'm glad it's now working for you!
